
input:
    host: "pulsar://localhost:6650"
    topic: "persistent://private/test-namespaces/users"
    codec: "json"


output:
    file:
        path: "/data/sub/"
    
    rdb:
        driver: "mysql"
        host: "127.0.0.1:3306"
        schema: "test_database"
        user: "root"
        password: "hogehoge123"
        statement: [
                "INSERT users (name, age, address) VALUE (?, ?, ?)",
                "name", "age", "address"
            ]

