
input:
    host: "pulsar://localhost:6650"
    topic: "persistent://private/test-namespaces/users"
    codec: "json"


output:
    file:
        input: "pulsar_input"
        path: "/data/sub/"
    
    rdb:
        driver: "mysql"
        host: "127.0.0.1:3306"
        schema: "test"
        user: "root"
        password: "password"
        statement: [
                "INSERT test-table (first-name, last-name, age, sex, address) VALUE (?, ?, ?, ?, ?)",
                "first-name", "last-name", "age", "sex, address"
            ]

