[source.a]
type = "$SOURCE_TYPE"
include = ["/data/sample/*.log"]
ignore_older_secs = 600
read_form = "beginning"

[sinks.a]
type = "pulsar"
inputs = ["a"]
endpoint = "$ENDPOINT"
topic="persistent://apache/pulsar/test-topic"
auth.name="token"
encoding.codec="$CODEC"
healthcheck.enabled = false
